services: 
  tester:
    build: 
      context: .
      target: test-e2e
    network_mode: "host"
    env_file:
      - path: .env.e2e
        required: false
    environment: 
      - API_URL=http://localhost:${PUBLIC_PORT:-3000}
