services:
  app: 
    build:
      target: dev
    env_file:
      - path: .env.dev
        required: false
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - INFRA_MODE=isolated
      - EXEC_MODE=dev

