name: global-e2e

services:
  global-e2e:
    build:
      context: . 
    environment:
      - NODE_ENV=test
      - CI=true
      - BACKEND_URL=http://backend:3000
      - FRONTEND_URL=http://frontend:8080
      - GATEWAY_URL=http://gateway:80
      - GATEWAY_PORT=${GATEWAY_PORT:-3000}
      - HOST_GATEWAY_URL=http://host.docker.internal:${GATEWAY_PORT:-3000}