services:
  firebase-emulator:
    image: spine3/firebase-emulator:latest
    environment:
      - GCP_PROJECT=demo-fullstack
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/"]
      interval: 3s
      timeout: 3s
      retries: 5
