services:
  mock-filesystem:
    image: wiremock/wiremock:3.9.1
    ports:
      - "3001:8080"
    volumes:
      - .docker/mocks/wiremock:/home/wiremock    
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:8080/__admin/mappings"]
      interval: 5s
      timeout: 5s
      retries: 5
